### ISSUE TITLE
dfmt linker error

### ISSUE THREAD

**Issue by nvankessel** [anglerud/aht20-driver#9]
I was unable to use this crate because the use of defmt in the lib.rs is giving linker errors. I removed all defmt calls in the lib.rs and then I could build the project.

can this be the possible problem: 
https://ferrous-systems.com/blog/defmt-rtt-linker-error/

**Comment by anglerud** [comment]
Thank you for the report, and the link - that definitely looks very relevant! I shall take a look by the weekend and try to fix this up!

**Comment by paologaleotti** [comment]
any info? i still have this issue

**Comment by anglerud** [comment]
> any info? i still have this issue

Version 1.2.2 has now been released with Andrew's feature flag! You can disable the default features (see the readme).
